### PR TITLE
Adding denom to counts

### PR DESCRIPTION
**Pull request by crussell-figure**
## Description

* Updated `AssetDetail.supply` from String to CoinStr
* Updated `AssetHolder.balance` to include `denom`
* Using actualy current height instead of deriving from signing infos

closes: #137

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/explorer/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by iramiller** [comment]
Shares are not coins. Rest of these seem to be good though. Not sure that shares should be exposed anyway… there is a recent discussion on the discord about this actually… it’s related to validator power and shares make that easier to calculate or something.

**Comment by crussell-figure** [comment]
> Shares are not coins. Rest of these seem to be good though. Not sure that shares should be exposed anyway… there is a recent discussion on the discord about this actually… it’s related to validator power and shares make that easier to calculate or something.

V true. Ill revert that

**Review by dwedul-figure — APPROVED** [review]
LGTM

**Review by channa-figure — APPROVED** [review]
LGTM

**Pull request merged**
