### PR TITLE
Update proto versions

### PR DESCRIPTION
**Pull request by fkneeland-figure**
## Description

We need to update some dependency versions.

closes: #152 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/explorer/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by crussell-figure — CHANGES_REQUESTED** [review]
You'll need to run the download protos task to bring them in, then fix any issues that arise with that.

**Review by channa-figure — APPROVED** [review]
LGTM

**Comment by fkneeland-figure** [comment]
@crussell-figure @channa-figure I ran the downloadProtos and it seems like everything worked fine?

**Review by dwedul-figure — DISMISSED** [review]
LGTM

**Review by crussell-figure — APPROVED** [review]
Fantastic!

**Pull request merged**
