### PR TITLE
Bug: Don't try to save missed blocks when current block height is 0

### PR DESCRIPTION
**Pull request by fkneeland-figure**
## Description

closes: #167

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/explorer/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by fkneeland-figure** [comment]
@crussell-figure This is a solution to a bug that @channa-figure figured out for a bug I ran into while running explorer service locally where I say the following error.  Idk if that properly addresses the issue or if there is an underlying problem for why we are calling that function when the block height is 0 that we need to address?

```
explorer-service     | io.grpc.StatusRuntimeException: INVALID_ARGUMENT: height must be greater than 0, but got 0: invalid request
explorer-service     | 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
explorer-service     | 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
explorer-service     | 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
explorer-service     | 	at cosmos.base.tendermint.v1beta1.ServiceGrpc$ServiceBlockingStub.getValidatorSetByHeight(ServiceGrpc.java:522)
explorer-service     | 	at io.provenance.explorer.grpc.v1.ValidatorGrpcClient.getValidatorsAtHeight(ValidatorGrpcClient.kt:76)
explorer-service     | 	at io.provenance.explorer.service.ValidatorService$saveMissedBlocks$1.invoke(ValidatorService.kt:357)
explorer-service     | 	at io.provenance.explorer.service.ValidatorService$saveMissedBlocks$1.invoke(ValidatorService.kt:44)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
explorer-service     | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
explorer-service     | 	at io.provenance.explorer.service.ValidatorService.saveMissedBlocks(ValidatorService.kt:352)
explorer-service     | 	at io.provenance.explorer.service.async.AsyncCaching.saveBlockEtc(AsyncCaching.kt:104)
explorer-service     | 	at io.provenance.explorer.service.async.AsyncService.updateLatestBlockHeightJob(AsyncService.kt:46)
explorer-service     | 	at jdk.internal.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
explorer-service     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
explorer-service     | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
explorer-service     | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
explorer-service     | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
explorer-service     | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
explorer-service     | 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
explorer-service     | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
explorer-service     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
explorer-service     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
explorer-service     | 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by crussell-figure** [comment]
If you want to bring this out of draft, ill approve and we can merge

**Comment by fkneeland-figure** [comment]
@crussell-figure I think this should be ready if it looks okay to you

**Comment by crussell-figure** [comment]
> @crussell-figure I think this should be ready if it looks okay to you

It needs a changelog entry. Also, in your commit, if you add `closes: #167 ` it will auto attach the issue and close it once its been merged

**Comment by fkneeland-figure** [comment]
@crussell-figure How does it look now?

**Review by crussell-figure — APPROVED** [review]

**Pull request merged**
